Repository galacticcouncil/HydraDX-node, pull requests merged in 2021-06, with the labels that each got.

#269 fix(amm): buy_price calculation
  Cargo.lock
  pallets/exchange/Cargo.toml
  pallets/exchange/benchmarking/Cargo.toml
  pallets/exchange/benchmarking/src/lib.rs
  pallets/exchange/src/tests.rs
  pallets/xyk/Cargo.toml
  pallets/xyk/src/benchmarking.rs
  pallets/xyk/src/lib.rs
  pallets/xyk/src/tests.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: bug

#270 feat: add fee to AMMTransfer
  Cargo.lock
  pallets/exchange/Cargo.toml
  pallets/exchange/benchmarking/src/lib.rs
  pallets/exchange/src/lib.rs
  pallets/exchange/src/tests.rs
  pallets/xyk/Cargo.toml
  pallets/xyk/src/benchmarking.rs
  pallets/xyk/src/lib.rs
  pallets/xyk/src/tests.rs
  primitives/Cargo.toml
  primitives/src/traits.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: enhancement

#277 feat!: multi payment fallback price
  Cargo.lock
  node/src/chain_spec.rs
  pallets/transaction-multi-payment/Cargo.toml
  pallets/transaction-multi-payment/benchmarking/Cargo.toml
  pallets/transaction-multi-payment/benchmarking/src/lib.rs
  pallets/transaction-multi-payment/benchmarking/src/mock.rs
  pallets/transaction-multi-payment/src/lib.rs
  pallets/transaction-multi-payment/src/mock.rs
  pallets/transaction-multi-payment/src/tests.rs
  pallets/transaction-multi-payment/src/traits.rs
  primitives/Cargo.toml
  primitives/src/traits.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: breaking-change

#271 fix(exchange): change pallet errors
  pallets/exchange/Cargo.toml
  pallets/exchange/src/lib.rs
  pallets/exchange/src/tests.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: bug

#281 docs: Update types config Readme
  README.md
Labels: documentation

#278 chore(xyk): use math from crates.io
  Cargo.lock
  pallets/xyk/Cargo.toml
Labels: chore

#286 chore: fix benchmarks build
  runtime/Cargo.toml
Labels: chore

#264 refactor: remove custom balances pallet
  Cargo.lock
  pallets/balances/Cargo.toml
  pallets/balances/README.md
  pallets/balances/src/benchmarking.rs
  pallets/balances/src/lib.rs
  pallets/balances/src/tests.rs
  pallets/balances/src/tests_composite.rs
  pallets/balances/src/tests_local.rs
  pallets/balances/src/tests_reentrancy.rs
  pallets/balances/src/weights.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: refactor

#283 chore!: v0.9.5
  .github/workflows/tests.yml
  Cargo.lock
  Cargo.toml
  node/Cargo.toml
  node/src/chain_spec.rs
  node/src/command.rs
  node/src/rpc.rs
  node/src/service.rs
  pallets/claims/src/mock.rs
  pallets/exchange/benchmarking/src/mock.rs
  pallets/exchange/src/mock.rs
  pallets/exchange/src/tests.rs
  pallets/faucet/src/mock.rs
  pallets/transaction-multi-payment/benchmarking/src/mock.rs
  pallets/transaction-multi-payment/src/mock.rs
  pallets/xyk/src/mock.rs
  pallets/xyk/src/tests.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
  rust-toolchain
Labels: breaking-change

#284 fix(xyk)!: change xyk pallet errors
  Cargo.lock
  pallets/exchange/src/tests.rs
  pallets/xyk/Cargo.toml
  pallets/xyk/src/lib.rs
  pallets/xyk/src/tests.rs
Labels: breaking-change
