Repository galacticcouncil/HydraDX-node, pull requests merged in 2021-04, with the labels that each got.

#199 fix!: offence is reported but slashing is not applied
  .gitignore
Labels: breaking-change

#200 fix!: set DOLLARS constant to correct number
  runtime/src/constants.rs
Labels: breaking-change

#202 feat: genesis history pallet
  Cargo.lock
  Cargo.toml
  README.md
  node/src/chain_spec.rs
  pallets/genesis-history/Cargo.toml
  pallets/genesis-history/src/lib.rs
  pallets/genesis-history/src/mock.rs
  pallets/genesis-history/src/tests.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: enhancement

#208 fix(runtime): add tx fee multiplier
  runtime/src/lib.rs
Labels: bug

#211 refactor(genesis-history): derived default genesis chain
  pallets/genesis-history/src/lib.rs
Labels: refactor

#194 feat: version consistent with tagged release
  Cargo.lock
  Cargo.toml
  node/Cargo.toml
  node/build.rs
  utils/build-script-utils/Cargo.toml
  utils/build-script-utils/src/git.rs
  utils/build-script-utils/src/lib.rs
  utils/build-script-utils/src/version.rs
Labels: enhancement

#216 fix(ci): tag version workflow
  .github/workflows/tests.yml
Labels: bug

#221 fix!: add election fallback on-chain
  Cargo.lock
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: breaking-change

#220 ci: automatically creates an EC2 instance for builds
  .github/workflows/tests.yml
  infrastructure/config_script.sh
  infrastructure/get_token.sh
  infrastructure/infra.tf
  infrastructure/run_conf.sh
Labels: ci

#212 feat: add tests for time units
  runtime/src/constants.rs
  runtime/src/lib.rs
Labels: enhancement
