Repository galacticcouncil/HydraDX-node, pull requests merged in 2021-12, with the labels that each got.

#342 chore: update weights and reference weights
  .maintain/bench-check/hydradx-bench-data.json
  node/Cargo.toml
  pallets/exchange/src/weights.rs
  pallets/transaction-multi-payment/src/weights.rs
  pallets/xyk/src/weights.rs
  runtime/hydra-dx/src/tests.rs
  scripts/check_performance.sh
Labels: chore

#344 ci: runtime upgrade test
  .github/workflows/tests.yml
  scripts/list_crate_updates.sh
Labels: ci

#345 chore: increase versions to avoid confict with snakenet
  Cargo.lock
  node/Cargo.toml
  primitives/Cargo.toml
  runtime/common/Cargo.toml
  runtime/hydradx/Cargo.toml
  runtime/hydradx/src/lib.rs
  runtime/testing-hydradx/Cargo.toml
  runtime/testing-hydradx/src/lib.rs
Labels: chore

#347 feat: add db benchmark to check perf script
  scripts/check_performance.sh
Labels: enhancement

#346 feat: add relaychain-info pallet
  Cargo.lock
  runtime/hydradx/Cargo.toml
  runtime/hydradx/src/lib.rs
  runtime/testing-hydradx/Cargo.toml
  runtime/testing-hydradx/src/lib.rs
Labels: enhancement
