Repository galacticcouncil/HydraDX-node, pull requests merged in 2021-07, with the labels that each got.

#293 ci: code coverage
  .github/workflows/tests.yml
Labels: ci

#294 test(xyk): add missing tests
  Cargo.lock
  pallets/xyk/src/lib.rs
  pallets/xyk/src/tests.rs
Labels: test

#289 feat!: update fee calculation
  Cargo.lock
  runtime/Cargo.toml
  runtime/src/constants.rs
  runtime/src/lib.rs
  runtime/src/tests.rs
Labels: breaking-change

#226 feat: create testing runtime
  Cargo.lock
  Cargo.toml
  README.md
  node/Cargo.toml
  node/src/chain_spec.rs
  node/src/cli.rs
  node/src/client.rs
  node/src/command.rs
  node/src/lib.rs
  node/src/main.rs
  node/src/service.rs
  node/src/testing_chain_spec.rs
  pallets/exchange/Cargo.toml
  pallets/exchange/src/lib.rs
  pallets/transaction-multi-payment/Cargo.toml
  pallets/transaction-multi-payment/src/lib.rs
  pallets/xyk/Cargo.toml
  pallets/xyk/src/lib.rs
  primitives/src/lib.rs
  runtime/common/Cargo.toml
  runtime/common/src/constants.rs
  runtime/common/src/lib.rs
  runtime/hydra-dx/Cargo.toml
  runtime/hydra-dx/build.rs
  runtime/hydra-dx/src/impls.rs
  runtime/hydra-dx/src/lib.rs
  runtime/hydra-dx/src/tests.rs
  runtime/testing-hydra-dx/Cargo.toml
  runtime/testing-hydra-dx/build.rs
  runtime/testing-hydra-dx/src/impls.rs
  runtime/testing-hydra-dx/src/lib.rs
Labels: enhancement
