Repository galacticcouncil/HydraDX-node, pull requests merged in 2021-03, with the labels that each got.

#173 feat!: set reward curve params for inc. testnet
  Cargo.lock
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: breaking-change

#170 chore(perf-check): install bench wizard as part of the check perf script
  scripts/check_performance.sh
Labels: chore

#174 feat!: setup technical committee
  node/src/chain_spec.rs
  runtime/src/constants.rs
  runtime/src/lib.rs
Labels: breaking-change

#179 bug(perf-check): fix bench-wizard install/upgrade
  scripts/check_performance.sh
Labels: bug

#163 feat!: add identity pallet
  Cargo.lock
  Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: breaking-change

#184 feat!: disable slashing
  Cargo.lock
  pallets/claims/src/lib.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: breaking-change

#187 feat!: change epoch to 4 hours
  Cargo.lock
  runtime/Cargo.toml
  runtime/src/constants.rs
  runtime/src/lib.rs
Labels: breaking-change, don't merge
