Repository galacticcouncil/HydraDX-node, pull requests merged in 2021-08, with the labels that each got.

#297 fix: Onboarding JSON fixes
  README.md
Labels: bug

#300 fix: add pool id to xyk pool created/destroyed events
  infrastructure/infra.tf
  pallets/exchange/src/tests.rs
  pallets/xyk/src/lib.rs
  pallets/xyk/src/tests.rs
Labels: bug

#301 ci: fix ami image
  infrastructure/config_script.sh
  infrastructure/get_token.sh
  infrastructure/infra.tf
  infrastructure/run_conf.sh
Labels: ci

#298 chore: v0.9.8
  Cargo.lock
  Cargo.toml
  node/Cargo.toml
  node/src/service.rs
  pallets/exchange/Cargo.toml
  pallets/exchange/src/lib.rs
  pallets/transaction-multi-payment/src/mock.rs
  runtime/common/Cargo.toml
  runtime/common/src/constants.rs
  runtime/hydra-dx/Cargo.toml
  runtime/hydra-dx/src/lib.rs
  runtime/hydra-dx/src/tests.rs
  runtime/testing-hydra-dx/Cargo.toml
  runtime/testing-hydra-dx/src/lib.rs
Labels: chore
