Repository galacticcouncil/HydraDX-node, pull requests merged in 2021-05, with the labels that each got.

#230 ci: Build workflow from fork PR
  .github/workflows/tests.yml
Labels: ci

#235 feat: change Price type
  Cargo.lock
  pallets/amm/Cargo.toml
  pallets/amm/src/benchmarking.rs
  pallets/amm/src/lib.rs
  pallets/amm/src/tests.rs
  pallets/amm/src/weights.rs
  pallets/exchange/benchmarking/src/lib.rs
  pallets/exchange/src/lib.rs
  pallets/exchange/src/tests.rs
  pallets/exchange/src/weights.rs
  pallets/transaction-multi-payment/benchmarking/src/lib.rs
  pallets/transaction-multi-payment/src/tests.rs
  pallets/transaction-multi-payment/src/weights.rs
  primitives/Cargo.toml
  primitives/src/lib.rs
  runtime/src/lib.rs
Labels: enhancement

#215 refactor(amm): changed event names to past tense
  README.md
  pallets/amm/README.md
  pallets/amm/src/lib.rs
  pallets/amm/src/tests.rs
  pallets/exchange/src/tests.rs
  runtime/Cargo.toml
Labels: refactor

#225 fix(node): configure justification import for full node
  .github/workflows/tests.yml
  node/Cargo.toml
  node/src/service.rs
Labels: bug

#224 chore: Substrate update
  Cargo.lock
  Cargo.toml
  node/Cargo.toml
  node/src/chain_spec.rs
  node/src/service.rs
  pallets/amm/Cargo.toml
  pallets/amm/src/lib.rs
  pallets/amm/src/mock.rs
  pallets/amm/src/tests.rs
  pallets/asset-registry/Cargo.toml
  pallets/asset-registry/src/mock.rs
  pallets/asset-registry/src/tests.rs
  pallets/balances/Cargo.toml
  pallets/balances/src/lib.rs
  pallets/claims/Cargo.toml
  pallets/claims/src/lib.rs
  pallets/claims/src/migration.rs
  pallets/claims/src/mock.rs
  pallets/claims/src/tests.rs
  pallets/exchange/Cargo.toml
  pallets/exchange/benchmarking/Cargo.toml
  pallets/exchange/benchmarking/src/lib.rs
  pallets/exchange/benchmarking/src/mock.rs
  pallets/exchange/src/direct.rs
  pallets/exchange/src/lib.rs
  pallets/exchange/src/mock.rs
  pallets/exchange/src/tests.rs
  pallets/faucet/Cargo.toml
  pallets/faucet/src/mock.rs
  pallets/genesis-history/Cargo.toml
  pallets/genesis-history/src/mock.rs
  pallets/transaction-multi-payment/Cargo.toml
  pallets/transaction-multi-payment/benchmarking/src/lib.rs
  pallets/transaction-multi-payment/benchmarking/src/mock.rs
  pallets/transaction-multi-payment/src/lib.rs
  pallets/transaction-multi-payment/src/mock.rs
  pallets/transaction-multi-payment/src/tests.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: chore

#239 fix(multi-payment): move balances dependency to dev-dependency
  Cargo.lock
  pallets/transaction-multi-payment/Cargo.toml
  pallets/transaction-multi-payment/benchmarking/Cargo.toml
Labels: bug

#241 fix!: set babe epoch config at genesis
  Cargo.lock
  node/Cargo.toml
  node/src/chain_spec.rs
  runtime/Cargo.toml
  runtime/src/constants.rs
  runtime/src/lib.rs
Labels: breaking-change

#238 docs: Code docs update
  .maintain/pallet-weight-template.hbs
  pallets/amm/README.md
  pallets/amm/rpc/runtime-api/src/lib.rs
  pallets/amm/rpc/src/lib.rs
  pallets/amm/src/lib.rs
  pallets/amm/src/mock.rs
  pallets/amm/src/tests.rs
  pallets/amm/src/weights.rs
  pallets/asset-registry/README.md
  pallets/asset-registry/src/lib.rs
  pallets/asset-registry/src/mock.rs
  pallets/asset-registry/src/tests.rs
  pallets/claims/README.md
  pallets/claims/src/benchmarking.rs
  pallets/claims/src/lib.rs
  pallets/claims/src/migration.rs
  pallets/claims/src/mock.rs
  pallets/claims/src/tests.rs
  pallets/claims/src/traits.rs
  pallets/claims/src/weights.rs
  pallets/exchange/benchmarking/src/amounts.rs
  pallets/exchange/benchmarking/src/lib.rs
  pallets/exchange/benchmarking/src/mock.rs
  pallets/exchange/src/direct.rs
  pallets/exchange/src/lib.rs
  pallets/exchange/src/mock.rs
  pallets/exchange/src/tests.rs
  pallets/exchange/src/weights.rs
  pallets/faucet/README.md
  pallets/faucet/src/lib.rs
  pallets/faucet/src/mock.rs
  pallets/faucet/src/tests.rs
  pallets/genesis-history/README.md
  pallets/genesis-history/src/lib.rs
  pallets/genesis-history/src/mock.rs
  pallets/genesis-history/src/tests.rs
  pallets/transaction-multi-payment/README.md
  pallets/transaction-multi-payment/benchmarking/src/lib.rs
  pallets/transaction-multi-payment/benchmarking/src/mock.rs
  pallets/transaction-multi-payment/src/lib.rs
  pallets/transaction-multi-payment/src/mock.rs
  pallets/transaction-multi-payment/src/tests.rs
  pallets/transaction-multi-payment/src/weights.rs
  primitives/src/asset.rs
  primitives/src/lib.rs
  primitives/src/traits.rs
  runtime/src/constants.rs
  runtime/src/impls.rs
  runtime/src/lib.rs
Labels: documentation

#247 fix(chore): discard patch for libsrock-db
  Cargo.lock
  Cargo.toml
Labels: bug

#254 refactor(build-script): allow to specify runtime
  node/build.rs
  utils/build-script-utils/src/version.rs
Labels: refactor

#246 feat: add utility pallet to allow batch txs execution
  Cargo.lock
  Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: enhancement

#242 refactor: pallet improvements and xyk pallet
  .github/workflows/tests.yml
  Cargo.lock
  Cargo.toml
  node/Cargo.toml
  node/src/rpc.rs
  pallets/asset-registry/src/lib.rs
  pallets/balances/src/benchmarking.rs
  pallets/exchange/Cargo.toml
  pallets/exchange/benchmarking/Cargo.toml
  pallets/exchange/benchmarking/src/lib.rs
  pallets/exchange/benchmarking/src/mock.rs
  pallets/exchange/src/mock.rs
  pallets/exchange/src/tests.rs
  pallets/transaction-multi-payment/Cargo.toml
  pallets/transaction-multi-payment/benchmarking/Cargo.toml
  pallets/transaction-multi-payment/benchmarking/src/lib.rs
  pallets/transaction-multi-payment/benchmarking/src/mock.rs
  pallets/transaction-multi-payment/src/mock.rs
  pallets/transaction-multi-payment/src/tests.rs
  pallets/xyk/Cargo.toml
  pallets/xyk/README.md
  pallets/xyk/rpc/Cargo.toml
  pallets/xyk/rpc/runtime-api/Cargo.toml
  pallets/xyk/rpc/runtime-api/src/lib.rs
  pallets/xyk/rpc/src/lib.rs
  pallets/xyk/src/benchmarking.rs
  pallets/xyk/src/lib.rs
  pallets/xyk/src/mock.rs
  pallets/xyk/src/tests.rs
  pallets/xyk/src/weights.rs
  primitives/src/lib.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: refactor

#259 refactor: revert price type to fixedu128
  Cargo.lock
  pallets/exchange/benchmarking/src/lib.rs
  pallets/exchange/src/tests.rs
  pallets/transaction-multi-payment/benchmarking/src/lib.rs
  pallets/transaction-multi-payment/src/tests.rs
  pallets/xyk/src/benchmarking.rs
  pallets/xyk/src/lib.rs
  pallets/xyk/src/tests.rs
  primitives/Cargo.toml
  primitives/src/lib.rs
Labels: refactor

#260 refactor: add traits to Fee struct
  Cargo.lock
  node/Cargo.toml
  pallets/asset-registry/Cargo.toml
  pallets/claims/Cargo.toml
  pallets/exchange/Cargo.toml
  pallets/exchange/benchmarking/Cargo.toml
  pallets/faucet/Cargo.toml
  pallets/transaction-multi-payment/Cargo.toml
  pallets/transaction-multi-payment/benchmarking/Cargo.toml
  pallets/xyk/Cargo.toml
  primitives/Cargo.toml
  primitives/src/lib.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: refactor

#257 ci: docker release workflow
  .dockerignore
  .github/workflows/docker.yml
  Dockerfile
  infrastructure/infra.tf
  stack.yml
Labels: ci

#263 fix!: WithFee::with_fee method
  Cargo.lock
  primitives/Cargo.toml
  primitives/src/lib.rs
  runtime/Cargo.toml
Labels: breaking-change

#262 feat(exchange)!: Update IntentionResolvedDirectTradeFees event
  pallets/exchange/Cargo.toml
  pallets/exchange/src/direct.rs
  pallets/exchange/src/lib.rs
  pallets/exchange/src/tests.rs
Labels: breaking-change

#266 feat(elections)!: added sane election setup
  Cargo.lock
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: breaking-change
