Repository galacticcouncil/HydraDX-node, pull requests merged in 2022-03, with the labels that each got.

#371 feat: add snakenet migration script
  scripts/snakenet-migration/README.md
  scripts/snakenet-migration/index.js
  scripts/snakenet-migration/package.json
Labels: enhancement

#372 chore: upgrade to polkadot-v0.9.16
  .github/workflows/tests.yml
  Cargo.lock
  node/Cargo.toml
  node/src/chain_spec/dev.rs
  node/src/chain_spec/local.rs
  node/src/chain_spec/mod.rs
  node/src/chain_spec/staging.rs
  node/src/chain_spec/testnet.rs
  node/src/command.rs
  node/src/service.rs
  node/src/testing_chain_spec.rs
  primitives/Cargo.toml
  primitives/src/constants.rs
  runtime/common/Cargo.toml
  runtime/common/src/lib.rs
  runtime/hydradx/Cargo.toml
  runtime/hydradx/src/lib.rs
  runtime/testing-hydradx/Cargo.toml
  runtime/testing-hydradx/src/lib.rs
Labels: chore

#375 feat: migration - triple balance and claims
  .gitignore
  scripts/snakenet-migration/index.js
  scripts/snakenet-migration/package.json
Labels: enhancement

#374 ci: fix incorrect output from version check
  scripts/list_crate_updates.sh
Labels: ci

#379 feat: snakenet migration of other modules
  scripts/snakenet-migration/index.js
  scripts/snakenet-migration/package.json
Labels: enhancement

#381 feat: added vesting account and lowered minimal vested transfer
  runtime/common/src/lib.rs
  runtime/hydradx/src/lib.rs
  runtime/hydradx/src/mock.rs
  runtime/hydradx/src/tests/mod.rs
  runtime/hydradx/src/tests/vested_transfer.rs
  runtime/testing-hydradx/src/lib.rs
  scripts/upgrade-runtime/index.js
  scripts/upgrade-runtime/package-lock.json
Labels: enhancement

#380 ci: version check can fail
  .github/workflows/tests.yml
Labels: ci

#384 fix: changed base OS in the dockerfile
  Dockerfile
Labels: bug

#387 fix: migration - use weight split
  scripts/snakenet-migration/index.js
Labels: bug
