Repository galacticcouncil/HydraDX-node, pull requests merged in 2022-04, with the labels that each got.

#395 fix: elections multi phase fallback
  Cargo.lock
  runtime/common/Cargo.toml
  runtime/common/src/constants.rs
  runtime/hydra-dx/Cargo.toml
  runtime/hydra-dx/src/lib.rs
  runtime/testing-hydra-dx/Cargo.toml
  runtime/testing-hydra-dx/src/lib.rs
Labels: bug

#397 feat: docker support for parachain
  .dockerignore
  .github/workflows/docker.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
  Dockerfile
  Makefile
  docker-compose.yml
  stack.yml
Labels: enhancement

#400 ci: semantic pr title validation action
  .github/workflows/semantic.yml
Labels: ci

#399 feat: collator rewards pallet
  Cargo.lock
  node/src/chain_spec/mod.rs
  node/src/testing_chain_spec.rs
  runtime/common/src/lib.rs
  runtime/hydradx/Cargo.toml
  runtime/hydradx/src/lib.rs
  runtime/testing-hydradx/Cargo.toml
  runtime/testing-hydradx/src/lib.rs
Labels: enhancement
