Repository galacticcouncil/HydraDX-node, pull requests merged in 2022-06, with the labels that each got.

#408 chore: normalize manifests of cargo package files
  node/Cargo.toml
  pallets/claims/Cargo.toml
  primitives/Cargo.toml
  runtime/common/Cargo.toml
  runtime/hydra-dx/Cargo.toml
  runtime/testing-hydra-dx/Cargo.toml
Labels: chore

#402 ci: Add check for code format
  .github/workflows/format.yml
  pallets/claims/src/lib.rs
  runtime/hydradx/src/xcm.rs
  runtime/testing-hydradx/src/xcm.rs
  utils/build-script-utils/src/git.rs
  utils/build-script-utils/src/lib.rs
  utils/build-script-utils/src/version.rs
Labels: ci

#414 Fix: update README about spinning up node with local testnet
  README.md
  rococo-local/testing-config.json
Labels: Fix

#413 feat: added multisig pallet
  Cargo.lock
  rococo-local/testing-config.json
  runtime/common/Cargo.toml
  runtime/common/src/lib.rs
  runtime/hydradx/Cargo.toml
  runtime/hydradx/src/lib.rs
  runtime/testing-hydradx/Cargo.toml
  runtime/testing-hydradx/src/lib.rs
Labels: enhancement

#401 feat: claim all staking rewards script
  scripts/claim-all-staking-rewards/index.js
  scripts/claim-all-staking-rewards/package.json
Labels: enhancement

#418 feat!: Use new collator-rewards pallet with SessionManager
  Cargo.lock
  node/Cargo.toml
  node/src/chain_spec/mod.rs
  node/src/testing_chain_spec.rs
  runtime/hydradx/Cargo.toml
  runtime/hydradx/src/lib.rs
  runtime/testing-hydradx/Cargo.toml
  runtime/testing-hydradx/src/lib.rs
Labels: breaking-change
