Repository galacticcouncil/HydraDX-node, pull requests merged in 2022-11, with the labels that each got.

#470 docs: try-runtime
  README.md
Labels: documentation

#468 feat: Add devnet chainspec
  Cargo.lock
  node/Cargo.toml
  node/res/devnet.json
  node/src/command.rs
  node/src/testing_chain_spec.rs
Labels: enhancement

#472 fix: omnipool asset trade state - derive typeinfo
  Cargo.lock
  pallets/omnipool/Cargo.toml
  pallets/omnipool/src/types.rs
  runtime/hydradx/Cargo.toml
  runtime/hydradx/src/lib.rs
  runtime/testing-hydradx/Cargo.toml
  runtime/testing-hydradx/src/lib.rs
Labels: bug

#473 chore: remove nft pallet from runtime
  Cargo.lock
  integration-tests/Cargo.toml
  runtime/hydradx/Cargo.toml
  runtime/hydradx/src/lib.rs
  runtime/testing-hydradx/Cargo.toml
  runtime/testing-hydradx/src/lib.rs
Labels: chore

#475 feat!: add XCM weight trader and update integration tests
  Cargo.lock
  integration-tests/Cargo.toml
  integration-tests/src/cross_chain_transfer.rs
  integration-tests/src/polkadot_test_net.rs
  runtime/hydradx/Cargo.toml
  runtime/hydradx/src/xcm.rs
  runtime/testing-hydradx/Cargo.toml
  runtime/testing-hydradx/src/xcm.rs
Labels: breaking-change

#477 feat: add uniques migration
  node/src/command.rs
  runtime/hydradx/src/lib.rs
  runtime/hydradx/src/migrations.rs
Labels: enhancement

#471 chore: upgrade to substrate v0.9.29
  Cargo.lock
  Cargo.toml
  Makefile
  integration-tests/Cargo.toml
  integration-tests/src/cross_chain_transfer.rs
  integration-tests/src/polkadot_test_net.rs
  node/Cargo.toml
  node/src/command.rs
  pallets/claims/Cargo.toml
  pallets/claims/src/weights.rs
  pallets/genesis-history/Cargo.toml
  pallets/omnipool/Cargo.toml
  pallets/omnipool/src/tests/invariants.rs
  pallets/omnipool/src/weights.rs
  primitives/Cargo.toml
  primitives/src/constants.rs
  runtime/common/Cargo.toml
  runtime/common/src/lib.rs
  runtime/common/src/weights/asset_registry.rs
  runtime/common/src/weights/balances.rs
  runtime/common/src/weights/claims.rs
  runtime/common/src/weights/collator_selection.rs
  runtime/common/src/weights/council.rs
  runtime/common/src/weights/currencies.rs
  runtime/common/src/weights/democracy.rs
  runtime/common/src/weights/identity.rs
  runtime/common/src/weights/payment.rs
  runtime/common/src/weights/preimage.rs
  runtime/common/src/weights/proxy.rs
  runtime/common/src/weights/scheduler.rs
  runtime/common/src/weights/system.rs
  runtime/common/src/weights/technical_comittee.rs
  runtime/common/src/weights/timestamp.rs
  runtime/common/src/weights/tokens.rs
  runtime/common/src/weights/transaction_multi_payment.rs
  runtime/common/src/weights/treasury.rs
  runtime/common/src/weights/utility.rs
  runtime/common/src/weights/vesting.rs
  runtime/common/src/weights/xcmp_queue.rs
  runtime/hydradx/Cargo.toml
  runtime/hydradx/src/lib.rs
  runtime/hydradx/src/migrations.rs
  runtime/hydradx/src/xcm.rs
  runtime/testing-hydradx/Cargo.toml
  runtime/testing-hydradx/src/lib.rs
  runtime/testing-hydradx/src/xcm.rs
Labels: chore

#465 feat: enable HDX transfers
  .github/workflows/tests.yml
  Cargo.lock
  node/Cargo.toml
  node/src/chain_spec/mod.rs
  rococo-local/testing-config.json
  runtime/hydradx/Cargo.toml
  runtime/hydradx/src/lib.rs
  runtime/testing-hydradx/Cargo.toml
  runtime/testing-hydradx/src/lib.rs
  scripts/upgrade-runtime/package.json
Labels: enhancement

#480 feat: make omnipool collection id constant
  Cargo.lock
  pallets/omnipool/Cargo.toml
  pallets/omnipool/src/lib.rs
  pallets/omnipool/src/tests/mock.rs
  runtime/hydradx/Cargo.toml
  runtime/hydradx/src/lib.rs
  runtime/testing-hydradx/Cargo.toml
  runtime/testing-hydradx/src/lib.rs
Labels: enhancement
