Repository galacticcouncil/HydraDX-node, pull requests merged in 2022-09, with the labels that each got.

#437 fix: omnipool - dont allow sell/buy with same asset in/out
  pallets/omnipool/src/lib.rs
  pallets/omnipool/src/tests/buy.rs
  pallets/omnipool/src/tests/sell.rs
Labels: bug

#443 fix: omnipool imbalance subtraction
  pallets/omnipool/src/tests/types.rs
  pallets/omnipool/src/types.rs
Labels: bug

#444 feat: omnipool - ensure imbalance is negative
  pallets/omnipool/src/lib.rs
Labels: enhancement

#449 fix: incorrect limit check when trading hub asset
  pallets/omnipool/src/lib.rs
  pallets/omnipool/src/tests/buy.rs
Labels: bug

#450 refactor: omnipool imbalance update
  pallets/omnipool/src/lib.rs
  pallets/omnipool/src/types.rs
Labels: refactor

#445 fix: correctly update hdx subpool hub reserve
  pallets/omnipool/src/lib.rs
  pallets/omnipool/src/tests/buy.rs
  pallets/omnipool/src/tests/mod.rs
  pallets/omnipool/src/tests/remove_liquidity.rs
  pallets/omnipool/src/tests/sell.rs
  pallets/omnipool/src/tests/verification/scenario_08.rs
  pallets/omnipool/src/tests/verification/scenario_10.rs
  pallets/omnipool/src/tests/verification/scenario_11.rs
Labels: bug

#451 fix: omnipool - dont allow LRNA refund
  pallets/omnipool/src/lib.rs
  pallets/omnipool/src/tests/refund.rs
Labels: bug

#457 fix: omnipool - allow only sell/buy as hub asset tradable state
  pallets/omnipool/src/lib.rs
  pallets/omnipool/src/tests/mod.rs
  pallets/omnipool/src/tests/tradability.rs
Labels: bug

#458 fix: check if stable asset is registered in init pool
  pallets/omnipool/src/lib.rs
  pallets/omnipool/src/tests/init_pool.rs
  pallets/omnipool/src/tests/mock.rs
Labels: bug

#459 fix: omnipool - ensure non-zero values
  pallets/omnipool/src/lib.rs
  pallets/omnipool/src/tests/mock.rs
  pallets/omnipool/src/tests/remove_liquidity.rs
Labels: bug

#462 refactor: omnipool - remove asset tvl
  Cargo.lock
  pallets/omnipool/Cargo.toml
  pallets/omnipool/src/lib.rs
  pallets/omnipool/src/tests/add_liquidity.rs
  pallets/omnipool/src/tests/add_token.rs
  pallets/omnipool/src/tests/buy.rs
  pallets/omnipool/src/tests/init_pool.rs
  pallets/omnipool/src/tests/invariants.rs
  pallets/omnipool/src/tests/mod.rs
  pallets/omnipool/src/tests/positions.rs
  pallets/omnipool/src/tests/remove_liquidity.rs
  pallets/omnipool/src/tests/sell.rs
  pallets/omnipool/src/tests/verification/scenario_04.rs
  pallets/omnipool/src/tests/verification/scenario_05.rs
  pallets/omnipool/src/tests/verification/scenario_06.rs
  pallets/omnipool/src/tests/verification/scenario_08.rs
  pallets/omnipool/src/tests/verification/scenario_09.rs
  pallets/omnipool/src/tests/verification/scenario_10.rs
  pallets/omnipool/src/tests/verification/scenario_11.rs
  pallets/omnipool/src/types.rs
Labels: refactor

#461 feat: add chain spec for rococo
  Cargo.lock
  node/Cargo.toml
  node/res/rococo.json
  node/src/chain_spec/mod.rs
  node/src/chain_spec/rococo.rs
  node/src/command.rs
Labels: enhancement
